#!/bin/sh
# get_star_index_GRCh38: download star index of GRCh38 Gencode transcriptome
BASE_DIR=$(pwd -P)

get_abs_path(){
  echo "$(cd $(dirname "${1}") && pwd -P)/$(basename "${1}")"
}

REPO_DIR="$(get_abs_path "${1}")"
REF_DIR="${REPO_DIR}/test/reference"

STAR_INDEX_URL="https://s3.amazonaws.com/nig-reference/GRCh38/star_index/star_GRCh38.tar.gz"
STAR_INDEX_GZIP_FILE_NAME="$(basename "${STAR_INDEX_URL}")"
STAR_INDEX_FILE_NAME="$(echo "${STAR_INDEX_GZIP_FILE_NAME}" | sed 's:.tar.gz$::')"

star_index_file_path="${REF_DIR}/star_index/GRCh38"

star_index_dir_path="$(dirname "${star_index_file_path}")"
star_index_file_name="$(basename "${star_index_file_path}")"

if test ! -e "${star_index_file_path}"; then
  mkdir -p "${star_index_dir_path}" && cd "${star_index_dir_path}"
  wget "${STAR_INDEX_URL}"
  tar zxf "${STAR_INDEX_GZIP_FILE_NAME}"
  mv "${STAR_INDEX_FILE_NAME}" "${star_index_file_name}"
  cd ${BASE_DIR}
fi

ln -s "${star_index_file_path}" "./star_GRCh38"
